dynamic-simulation-default-parameters:
  startTime: 0
  stopTime: 30

dynawaltz:
  debug: true

dynawaltz-default-parameters:
  # All the pathes can be relative to the root directory
  parametersFile: groovy/models.par
  network.parametersFile: groovy/network.par
  network.parametersId: "8"
  solver.type: IDA
  solver.parametersFile: groovy/solver.par
  solver.parametersId: "2"

